import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/footer";
import Prefooter from "@/components/prefooter";

const chillax = localFont({
  src: "./fonts/Chillax-Variable.ttf",
  variable: "--font-chillax",
  display: "swap",
  weight: "200 700",
});

const zodiak = localFont({
  src: [
    {
      path: "./fonts/Zodiak-Thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/Zodiak-ThinItalic.otf",
      weight: "100",
      style: "italic",
    },
    {
      path: "./fonts/Zodiak-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Zodiak-LightItalic.otf",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/Zodiak-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Zodiak-Italic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/Zodiak-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Zodiak-BoldItalic.otf",
      weight: "700",
      style: "italic",
    },
    {
      path: "./fonts/Zodiak-Extrabold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/Zodiak-ExtraboldItalic.otf",
      weight: "800",
      style: "italic",
    },
    {
      path: "./fonts/Zodiak-Black.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/Zodiak-BlackItalic.otf",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-zodiak",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${chillax.variable} ${zodiak.variable} h-full antialiased`}>
      <body className="min-h-full max-w-dvw flex flex-col font-sans bg-[#000C04]">
        {children}
        <Prefooter />
        <Footer />
      </body>
    </html>
  );
}
